# Set the path to our board's root directory
BOARD_SW_ROOT=../..

# Declare sources for the driver before we include everything
COMPILE_SRCS=usbhostslave-host.c usbhostslave-slave.c

include $(BOARD_SW_ROOT)/Makefile.inc

clean:
	$(Q)rm -f *.a *.o
